### ISSUE TITLE
Support logging in json format

### ISSUE THREAD

**Issue by jhuntwork** [VirtusLab/kubedrainer#6]
In our clusters we use fluentbit to send logs to CloudWatch, which then allows us to use CloudWatch Logs Insights to query for patterns, either for one-time debugging or auditing, or in some cases, even creating Grafana dashboards. Having the option to output the logs in json format allows for improved searching on specific fields or patterns.

Taking this on would likely mean using a different logging package, since it doesn't look like glog supports this. I've had good success in the past with [logrus](https://github.com/sirupsen/logrus), but it looks like even they now recommend some other improved packages, such as: [Zerolog](https://github.com/rs/zerolog), [Zap](https://github.com/uber-go/zap), and [Apex](https://github.com/apex/log).

**Comment by pawelprazak** [comment]
Yes, `glog` was used AFAIR because it was already there in the kubernetes client. What would you choose?

**Comment by jhuntwork** [comment]
Of those that I've used, [zerolog]( https://github.com/rs/zerolog) seemed to me the right combination of usability and performance

**Comment by pawelprazak** [comment]
Would you like to create a PR for this? :)

**Comment by jhuntwork** [comment]
Sure :) Would you like it to be json as the default, or as an option?

**Comment by pawelprazak** [comment]
Makes sense, as it will run on Kubernetes. If it makes sense to you as the default as well then I think there's no need to overthink it ;)
